[tox]
envlist = py3.{9-13}-chainladder0.8.{24, 23, 22, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0}

[testenv]
# install pytest in the virtualenv where commands will be executed
deps =
    pytest
    sparse<0.16
commands =
    # NOTE: you can run any command line tool here - not just tests
    pytest {posargs:tests}

[testenv:chainladder]
description = run tests with multiple versions
deps =
    0.8.24: chainladder==0.8.24
    0.8.23: chainladder==0.8.23
    0.8.22: chainladder==0.8.22
    0.8.20: chainladder==0.8.20
    0.8.19: chainladder==0.8.19
    0.8.18: chainladder==0.8.18
    0.8.17: chainladder==0.8.17
    0.8.16: chainladder==0.8.16
    0.8.15: chainladder==0.8.15
    0.8.14: chainladder==0.8.14
    0.8.13: chainladder==0.8.13
    0.8.12: chainladder==0.8.12
    0.8.11: chainladder==0.8.11
    0.8.10: chainladder==0.8.10
    0.8.9: chainladder==0.8.9
    0.8.8: chainladder==0.8.8
    0.8.7: chainladder==0.8.7
    0.8.6: chainladder==0.8.6
    0.8.5: chainladder==0.8.5
    0.8.4: chainladder==0.8.4
    0.8.3: chainladder==0.8.3
    0.8.2: chainladder==0.8.2
    0.8.1: chainladder==0.8.1
    0.8.0: chainladder==0.8.0
commands =
    pytest {posargs:tests}